### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by catamphetamine** [theKashey/focus-lock#70] opened 2024-04-21 08:08 UTC
On the NPM website it says that the package is deprecated:

![image](https://github.com/theKashey/focus-lock/assets/477167/f4403b1a-4bb2-4b6f-b778-93e2b4b4f215)

In the console:

```
ERROR in ./node_modules/react-focus-lock/dist/es2015/index.js 1:0-38
Module not found: Error: Can't resolve './Combination' in 'C:\dev\anychan\node_modules\react-focus-lock\dist\es2015'
Did you mean 'Combination.js'?
BREAKING CHANGE: The request './Combination' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve './Combination' in 'C:\dev\anychan\node_modules\react-focus-lock\dist\es2015'
  using description file: C:\dev\anychan\node_modules\react-focus-lock\package.json (relative path: ./dist/es2015)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\dev\anychan\node_modules\react-focus-lock\package.json (relative path: ./dist/es2015/Combination)
      Field 'browser' doesn't contain a valid alias configuration
      C:\dev\anychan\node_modules\react-focus-lock\dist\es2015\Combination doesn't exist
 @ ./node_modules/social-components-react/components/Slideshow.js 6:0-41 347:30-39
 @ ./src/components/Slideshow.js 8:0-72 33:30-39
 @ ./src/pages/Application.js 18:0-51 215:35-44
 @ ./src/routes.js 4:0-49 17:19-30
 @ ./src/react-pages.js 4:0-33 15:8-14
 @ ./src/render.js 6:0-51 14:45-64
 @ ./src/index.js 35:0-36 56:10-19
```

Workaround:

```
yarn add react-focus-lock@^2.11.0
```

**Comment by theKashey** [comment] 2024-04-21 23:50
Duplicate of https://github.com/theKashey/react-focus-lock/issues/301
(and that is a different repository)

**Closed by theKashey** 2024-04-21 23:50 UTC
